const requiredFortunes = [
  'The lows are what makes the highs higher.',
  'No good deed goes unpunished.',
  'Some doors close because your hands are full.',
  'Your next brave choice may look ordinary.',
  'A quiet no can protect a louder yes.',
  'The delay is not always the damage.',
  'You are allowed to outgrow your old wishes.',
  'Bad timing can still teach good aim.',
  'Not every loss deserves a lesson today.',
  'Your patience is becoming a private advantage.',
  'A difficult truth can still set you free.',
  'Small courage compounds when nobody applauds.',
  'The wrong room can sharpen your direction.',
  'Rest before resentment writes your next decision.',
  'Even good seasons ask for pruning.',
  'The answer may arrive dressed as discipline.',
  'Hope works best with honest hands.',
  'Some blessings first appear as interruptions.',
  'A closed fist cannot receive better things.',
  'You can begin without feeling ready.',
];

const extraFortunes = [
  'Let the hard day make your roots deeper.',
  'A wise pause can save a whole season.',
  'Your next chapter may prefer a quieter entrance.',
  'Do not mistake survival for your final form.',
  'The heart learns strength by staying open carefully.',
  'A little darkness can make direction visible.',
  'Choose the truth that lets you breathe again.',
  'Your peace may disappoint people who used access.',
  'Even a cracked plan can hold a blessing.',
  'Let the lesson mature before naming the loss.',
];

const subjects = [
  'Your quiet effort',
  'A difficult morning',
  'The choice you avoid',
  'Your next apology',
  'The smallest promise',
  'A lonely season',
  'Your honest boundary',
  'The work unseen',
  'A delayed answer',
  'Your tired heart',
  'One clear decision',
  'The mistake lingering',
  'Your private discipline',
  'A strange detour',
  'The person leaving',
  'Your sharper question',
  'A softer voice',
  'The risk ahead',
  'Your old fear',
  'A hard ending',
  'The truth arriving',
  'Your better habit',
  'A broken plan',
  'The silence after',
  'Your careful patience',
  'A painful no',
  'The boring work',
  'Your hidden courage',
  'A failed attempt',
  'The burden shared',
  'Your next sunrise',
  'A cancelled plan',
  'The door closing',
  'Your slow progress',
  'A restless night',
  'The right refusal',
  'Your kinder thought',
  'A missed chance',
  'The heavy lesson',
  'Your daily practice',
  'A rough beginning',
  'The pause today',
  'Your wiser hunger',
  'A bruised ambition',
  'The doubt speaking',
  'Your clean intention',
  'A bitter truth',
  'The road bending',
  'Your steady return',
  'A humble win',
];

const predicates = [
  'may become tomorrow\'s most useful advantage.',
  'can turn today\'s pressure into clearer purpose.',
  'will make future joy feel better earned.',
  'may reveal the courage you already carried.',
  'can save tomorrow from an old mistake.',
  'is quietly building a stronger inner compass.',
  'may cost less than another year pretending.',
  'can open the smaller door you needed.',
  'is making your aim cleaner under pressure.',
  'may expose comfort that was costing you.',
  'will ask for courage before it rewards.',
  'can soften you without making you surrender.',
  'may become proof that patience was working.',
  'will test whether your appetite is honest.',
  'can make room for a calmer future.',
  'is proof you kept moving through uncertainty.',
  'may protect the version of you arriving.',
  'can become wisdom you actually use.',
  'is teaching timing you could not rush.',
  'will reveal strength you stopped performing.',
];

const observations = [
  'You do not need permission to begin again.',
  'The easy road may invoice you later.',
  'Let the next step be smaller than pride.',
  'A calm answer can still be powerful.',
  'Do not confuse noise with momentum.',
  'A bitter season can sweeten your aim.',
  'The mirror is kinder after honest work.',
  'You may be grieving a future, not failure.',
  'Some victories arrive without witnesses.',
  'The truth rarely needs a costume.',
  'Make peace with the pace that lasts.',
  'A sharp setback can cut a clearer path.',
  'You can miss something and still choose forward.',
  'Let discipline carry what motivation drops.',
  'The wrong yes can become expensive.',
  'Your future self remembers today kindly.',
  'A small repair can save a whole bridge.',
  'Do not water what only drains you.',
  'Even luck prefers a prepared table.',
  'A heavy week can still hold mercy.',
  'Some people clap only when you shrink.',
  'You are not late to your own life.',
  'The lesson may be boundaries, not forgiveness.',
  'Small joy is still legitimate evidence.',
  'A closed door can be clean mercy.',
  'You can be kind and still leave.',
  'Do not romanticize what repeatedly hurts you.',
  'Better standards will feel lonely first.',
  'The mountain changes when your breath steadies.',
  'A quiet comeback still counts.',
  'Your doubt is not always the judge.',
  'Let the bruise become information, not identity.',
  'The first honest sentence changes the room.',
  'You can forgive without reopening the door.',
  'A slow bloom is still a bloom.',
  'The wrong audience makes courage look foolish.',
  'Let today be evidence, not a verdict.',
  'Your limits are not moral failures.',
  'A clean ending can still ache.',
  'The path improves when comparison leaves.',
  'Do not let comfort impersonate peace.',
  'A hard no can guard a sacred yes.',
  'Your consistency is louder than your announcement.',
  'The wound may close before the story does.',
  'Not every invitation deserves your energy.',
  'A quiet life can still be legendary.',
  'The best revenge is becoming unavailable.',
  'Your attention is a form of wealth.',
  'A setback can be a disguised edit.',
  'Some storms only prove the roof works.',
];

const prompts = [
  'Choose the thing your future can thank.',
  'Spend your courage where it earns peace.',
  'Trust the pattern, but verify the promise.',
  'Leave before bitterness starts decorating the room.',
  'Keep the lesson; release the performance.',
  'Let tomorrow inherit one cleaner choice.',
  'Ask for more, then become more ready.',
  'Protect the dream from casual opinions.',
  'Walk slowly where your spirit gets honest.',
  'Trade panic for one useful action.',
  'Let the silence show who listens.',
  'Do the humble thing extremely well.',
  'Give your attention to what returns life.',
  'Refuse the version that requires self-betrayal.',
  'Let the hard answer simplify you.',
  'Practice hope like it is a skill.',
  'Make the apology before pride rehearses.',
  'Choose repair when escape becomes a habit.',
  'Let success arrive without explaining itself.',
  'Hold the standard even when lonely.',
  'Question the comfort that keeps you small.',
  'Let your effort become your receipt.',
  'Start before the perfect mood appears.',
  'Be careful what you normalize.',
  'Trust kindness, but keep your eyes open.',
  'Let the loss teach without leading.',
  'Build the life your excuses fear.',
  'Say less where actions already confess.',
  'Choose the peace that costs your ego.',
  'Let time reveal what pressure cannot.',
  'Keep moving; clarity prefers motion.',
  'Stop negotiating with repeated disrespect.',
  'Let your next yes be clean.',
  'Do not outsource your inner weather.',
  'Turn envy into instructions.',
  'Keep one promise to yourself today.',
  'Let the closed chapter stay closed.',
  'Practice becoming easier to trust.',
  'Make room before asking for more.',
  'Choose proof over potential today.',
  'Let your pace embarrass nobody.',
  'Do not feed every fear a calendar.',
  'Give grief a chair, not the throne.',
  'Invest where your effort is respected.',
  'Let your boundaries speak before resentment shouts.',
  'Choose patience without choosing passivity.',
  'Let the future find you prepared.',
  'Stop polishing what should be released.',
  'Let honesty shorten the distance home.',
  'Carry ambition without abandoning tenderness.',
];

const cautions = [
  'Not every helper is helping.',
  'Some bridges burn because they were traps.',
  'A pretty promise can still be debt.',
  'Your comfort zone may charge compound interest.',
  'Some apologies only reset the same harm.',
  'Being needed can become a cage.',
  'The crowd can be confidently wrong.',
  'A familiar pain is still pain.',
  'Some loyalty is just fear wearing perfume.',
  'Winning badly can still make you smaller.',
  'A rushed blessing can become a burden.',
  'Not every open door respects your future.',
  'Some silence is strategy; some is neglect.',
  'The easiest yes may steal your year.',
  'A bright mask can hide poor foundations.',
  'Some exits look rude before they look wise.',
  'Approval can become the most expensive addiction.',
  'A soft heart still needs locked doors.',
  'Some lessons repeat because comfort keeps enrolling.',
  'Being chosen is not always being valued.',
  'A golden cage is still a cage.',
  'Some people miss you as a service.',
  'The wrong dream can exhaust the right person.',
  'A delayed consequence is still a consequence.',
  'Not every wound becomes wisdom automatically.',
  'A cheap win can cost your character.',
  'Some invitations are tests, not opportunities.',
  'Overexplaining can become self-abandonment.',
  'The loudest room may know the least.',
  'A second chance can become a pattern.',
  'Some comfort is only fear with furniture.',
  'The shortcut may remember your address.',
  'A polished lie still collects interest.',
  'Some endings are mercy with bad manners.',
  'Hope without action can become decoration.',
  'A bad fit can still flatter you.',
  'Some praise wants to purchase your obedience.',
  'The wrong peace asks you to disappear.',
  'A repeated excuse is a decision.',
  'Some opportunities arrive carrying old chains.',
  'A small compromise can grow teeth.',
  'The rescue role can drown the rescuer.',
  'Some dreams expire when self-respect arrives.',
  'Being understood is not owed by everyone.',
  'A kind face can still bring chaos.',
  'Some delays are protection with poor branding.',
  'The past can knock without getting invited.',
  'A perfect plan can hide cowardice.',
  'Some wins are warnings in costume.',
  'The wrong person can make peace feel boring.',
];

const dailyStarts = [
  'Your next brave step',
  'The honest work today',
  'A gentler kind of courage',
  'The promise you keep privately',
  'Your willingness to begin again',
  'A calmer answer tomorrow',
  'The patience you practice now',
  'Your refusal to disappear',
  'A better question tonight',
  'The boundary you hold',
  'Your smallest sincere effort',
  'A quiet act of faith',
  'The repair you choose',
  'Your discipline after disappointment',
  'A cleaner kind of ambition',
  'The truth you finally name',
  'Your care for the details',
  'A simple honest habit',
  'The courage to pause',
  'Your attention to what matters',
  'A softer way forward',
  'The standard you protect',
];

const dailyEndings = [
  'can make the map appear.',
  'may teach your fear manners.',
  'will make tomorrow feel earned.',
  'can return you to yourself.',
  'may open without force.',
];

const reflectiveStarts = [
  'The thing you lost',
  'The answer that stalled',
  'The room that rejected you',
  'The dream that changed shape',
  'The no that embarrassed you',
  'The plan that collapsed',
  'The silence that followed',
  'The ache you keep carrying',
  'The chance that passed',
  'The apology never offered',
  'The praise you wanted',
  'The comfort you outgrew',
  'The certainty you missed',
  'The lesson that returned',
  'The pressure you survived',
  'The hope that flickered',
  'The door that vanished',
  'The shortcut you refused',
  'The mistake you studied',
  'The grief you respected',
  'The doubt that visited',
  'The burden you named',
];

const reflectiveEndings = [
  'may still become useful light.',
  'can sharpen merciful aim.',
  'may protect a better version.',
  'can teach beyond comfort.',
  'may leave room for cleaner joy.',
];

const sharpStarts = [
  'Some people return',
  'Some doors reopen',
  'Some praise arrives',
  'Some chances sparkle',
  'Some comfort lingers',
  'Some victories glitter',
  'Some apologies land',
  'Some invitations flatter',
  'Some shortcuts shine',
  'Some endings hurt',
  'Some promises bloom',
  'Some advice sounds wise',
  'Some loyalties feel noble',
  'Some storms pass',
  'Some gifts arrive',
  'Some dreams demand',
  'Some attention feels warm',
  'Some routines feel safe',
  'Some bargains look harmless',
  'Some silence feels peaceful',
  'Some help feels generous',
  'Some love feels familiar',
];

const sharpEndings = [
  'only to test your progress.',
  'with the same old invoice.',
  'because your standards got louder.',
  'before the lesson is complete.',
  'and still deserve suspicion.',
];

function combine(starts, endings, limit) {
  return starts.flatMap((start) =>
    endings.map((ending) => `${start} ${ending}`)
  ).slice(0, limit);
}

const rogueSubjects = [
  'Ambition',
  'Charm',
  'Comfort',
  'Discipline',
  'Envy',
  'Fear',
  'Forgiveness',
  'Gossip',
  'Hunger',
  'Instinct',
  'Jealousy',
  'Kindness',
  'Luck',
  'Loyalty',
  'Patience',
  'Peace',
  'Pride',
  'Regret',
  'Revenge',
  'Silence',
  'Success',
  'Temptation',
  'Trust',
  'Truth',
  'Vanity',
  'Wisdom',
  'Your backbone',
  'Your boundary',
  'Your comeback',
  'Your doubt',
  'Your glow',
  'Your grief',
  'Your hunger',
  'Your instinct',
  'Your peace',
  'Your restraint',
  'Your shadow',
  'Your standards',
  'Your timing',
  'Your wound',
];

const rogueTargets = [
  'a cheap apology',
  'a borrowed dream',
  'a pretty excuse',
  'a golden cage',
  'a stale promise',
  'a loud opinion',
  'a soft betrayal',
  'a familiar trap',
  'a rented identity',
  'a thirsty audience',
  'a polished lie',
  'a hungry secret',
  'a crooked shortcut',
  'a fragile throne',
  'a flattering leash',
  'a recycled lesson',
  'an old costume',
  'an easy villain',
  'someone else\'s chaos',
  'yesterday\'s permission',
  'borrowed confidence',
  'public approval',
  'private disrespect',
  'fake urgency',
  'convenient loyalty',
  'decorated fear',
  'comfortable misery',
  'performative peace',
  'expired guilt',
  'beautiful nonsense',
];

const rogueVerbs = [
  'chase',
  'crown',
  'defend',
  'feed',
  'follow',
  'forgive',
  'glorify',
  'ignore',
  'marry',
  'mistake',
  'obey',
  'polish',
  'protect',
  'reheat',
  'romanticize',
  'serve',
  'trust',
  'worship',
  'water',
  'wear',
];

const rogueCosts = [
  'costs your calm',
  'shrinks your future',
  'taxes your spirit',
  'borrows your spine',
  'eats your morning',
  'dulls your hunger',
  'mocks your standards',
  'rents your attention',
  'cheapens your yes',
  'crowds your peace',
  'sells your silence',
  'flatters your fear',
  'drains your magic',
  'delays your becoming',
  'teaches the wrong lesson',
  'keeps score badly',
  'smiles while stealing',
  'leaves fingerprints',
  'comes with interest',
  'knows your weakness',
];

const rogueMasks = [
  'fear wearing manners',
  'ego wearing perfume',
  'envy wearing concern',
  'panic wearing productivity',
  'control wearing care',
  'chaos wearing chemistry',
  'guilt wearing loyalty',
  'pride wearing standards',
  'avoidance wearing peace',
  'cowardice wearing strategy',
  'hunger wearing destiny',
  'boredom wearing romance',
  'betrayal wearing timing',
  'noise wearing importance',
  'debt wearing opportunity',
  'weakness wearing forgiveness',
  'vanity wearing ambition',
  'comfort wearing wisdom',
  'control wearing devotion',
  'damage wearing history',
];

const rogueConditions = [
  'the room goes quiet',
  'the apology feels rehearsed',
  'the shortcut gets charming',
  'the praise sounds hungry',
  'the old door knocks',
  'the pattern repeats',
  'the crowd claps too early',
  'the lesson starts flirting',
  'the truth ruins dinner',
  'the silence feels expensive',
  'the offer smells desperate',
  'the dream demands obedience',
  'the villain sounds reasonable',
  'the blessing feels rushed',
  'the easy yes sparkles',
  'the mask fits perfectly',
  'the gossip comes gift-wrapped',
  'the comfort gets possessive',
  'the apology skips repair',
  'the exit looks dramatic',
  'your ego wants witnesses',
  'your peace starts bargaining',
  'your standards feel lonely',
  'your intuition gets rude',
  'your patience becomes a cage',
  'your kindness gets exploited',
  'your ambition gets thirsty',
  'your past sends flowers',
  'your fear quotes logic',
  'your hunger gets reckless',
];

const rogueCommands = [
  'leave with clean hands',
  'take the smaller crown',
  'protect the quiet win',
  'let them misunderstand',
  'keep your receipt',
  'question the sparkle',
  'save your good name',
  'do not clap yet',
  'walk before worshipping',
  'choose the harder peace',
  'let the mask sweat',
  'spend no more soul',
  'make truth pay rent',
  'stop auditioning for scraps',
  'let silence testify',
  'refuse the pretty trap',
  'keep the door boring',
  'make chaos show ID',
  'guard your morning',
  'trust the bruise',
];

const rogueEndings = [
  'keeps receipts better than memory.',
  'turns poison into useful ink.',
  'looks rude before it looks royal.',
  'knows when the crown is cursed.',
  'does not negotiate with crumbs.',
  'saves mercy for honest mouths.',
  'can smell a pretty trap.',
  'makes weak rooms nervous.',
  'leaves before the bill arrives.',
  'laughs at recycled warnings.',
  'keeps the throne under review.',
  'will not babysit bad patterns.',
  'knows gold can still be bait.',
  'charges interest on disrespect.',
  'turns shade into better posture.',
];

const rogueOneLiners = [
  'Blessings with teeth still count.',
  'Burn the bridge if it charges rent.',
  'Do not romanticize a repeat offender.',
  'Even gold can smell like a trap.',
  'Every crown has a cancellation policy.',
  'Good taste can save your life.',
  'Gratitude is not a leash.',
  'Hold the line; let them perform.',
  'If peace feels expensive, audit the room.',
  'Jealousy is just unpaid research.',
  'Keep receipts, but stop rereading them.',
  'Let envy become a business plan.',
  'Never confuse chemistry with character.',
  'No throne is worth your nervous system.',
  'Polite poison is still poison.',
  'Rejection can be concierge-level protection.',
  'Some apologies are just costume changes.',
  'Some blessings arrive wearing bad manners.',
  'Some chaos calls itself passion.',
  'Some crowns are just shiny cages.',
  'Some doors deserve a deadbolt.',
  'Some friendships expire without announcing it.',
  'Some gifts come with hidden invoices.',
  'Some lessons deserve no encore.',
  'Some people miss your usefulness, not you.',
  'Some praise is bait with perfume.',
  'Some shortcuts know your address.',
  'Some silence is premium self-respect.',
  'Some storms are just unpaid drama.',
  'Stop feeding rooms that starve you.',
  'The bait knows what you want.',
  'The crown is lighter without approval.',
  'The glow-up begins with one blocked number.',
  'The loudest warning may wear lipstick.',
  'The wrong yes steals weekends.',
  'Trust the exit that restores oxygen.',
  'Your comeback does not need a parade.',
  'Your enemy may be your appetite.',
  'Your peace deserves armed security.',
  'Your standards are not a group project.',
  'A fake friend claps with cold hands.',
  'A quiet exit can be a masterpiece.',
  'A soft heart still needs locks.',
  'A villain can bring useful maps.',
  'Ambition without taste becomes public noise.',
  'Better alone than professionally drained.',
  'Bitter truth beats sweet confusion.',
  'Cheap attention has expensive side effects.',
  'Closure sometimes looks like blocking access.',
  'Confidence without receipts is just theatre.',
  'Do not decorate your own cage.',
  'Do not finance someone else\'s chaos.',
  'Do not pet the old snake.',
  'Drama is debt with better lighting.',
  'Even mercy needs office hours.',
  'Familiar pain is still a scam.',
  'Forgiveness does not include free parking.',
  'Hope is not a hostage agreement.',
  'Kindness without boundaries becomes unpaid labor.',
  'Let bad timing stay embarrassed.',
  'Let karma cook without your supervision.',
  'Let loyalty survive the audit.',
  'Let rejection do its security job.',
  'Never chase what enjoys running.',
  'Never crown a pattern as destiny.',
  'Never downsize your spirit for company.',
  'Never lease your peace to panic.',
  'Never mistake access for affection.',
  'Never worship potential without proof.',
  'No is a complete sentence with jewelry.',
  'Not every spark deserves oxygen.',
  'Old chaos loves a fresh outfit.',
  'Peace gets louder after you stop explaining.',
  'Potential is not a payment plan.',
  'Private disrespect cancels public charm.',
  'Protect the blessing from bored opinions.',
  'Raise the standard; shrink the guest list.',
  'Revenge is often just delayed self-sabotage.',
  'Say less; let consequences speak fluently.',
  'Self-respect looks expensive to cheap people.',
  'Some exits are emergency blessings.',
  'Some miracles require a blocked contact.',
  'Some people bring weather, not love.',
  'Some wins are warnings with confetti.',
  'Stop calling chaos chemistry.',
  'Stop dating the lesson after graduation.',
  'The apology needs rent money.',
  'The best flex is nervous-system peace.',
  'The block button is modern incense.',
  'The cheap seat has loud opinions.',
  'The lesson gets louder when ignored.',
  'The mask always sweats eventually.',
  'The wrong crowd makes wisdom look boring.',
  'Their confusion is not your homework.',
  'Truth ages better than charm.',
  'Walk away before resentment learns your handwriting.',
  'When the bait sparkles, check the hook.',
  'Winning quietly still ruins their forecast.',
  'You can be grateful and unavailable.',
  'You can be kind without being edible.',
  'You do not owe access for history.',
  'You outgrew what used to impress you.',
  'Your absence may be the medicine.',
  'Your blessing may require stricter doors.',
  'Your body keeps score better than excuses.',
  'Your glow does not need permission.',
  'Your intuition is not being dramatic.',
  'Your peace is not a community asset.',
  'Your silence can be an invoice.',
  'Your soft era still needs boundaries.',
  'Your standards are the spell.',
  'Your throne needs fewer visitors.',
  'Your villain may be the mirror.',
  'A beautiful apology still needs changed behavior.',
  'A calm nervous system is luxury.',
  'A closed tab can save a life.',
  'A compliment can still be a leash.',
  'A delayed win ages like revenge.',
  'A messy blessing still outranks a polished trap.',
  'A private win hits harder.',
  'A throne without peace is furniture.',
];

function buildRogueFortunes() {
  return [
    ...rogueOneLiners,
    ...rogueSubjects.flatMap((subject) =>
      rogueEndings.map((ending) => `${subject} ${ending}`)
    ),
    ...rogueVerbs.flatMap((verb) =>
      rogueTargets.map((target) => `Never ${verb} ${target}.`)
    ),
    ...rogueTargets.flatMap((target) =>
      rogueCosts.map((cost) => `${capitalize(target)} ${cost}.`)
    ),
    ...rogueSubjects.flatMap((subject) =>
      rogueMasks.map((mask) => `${subject} can be ${mask}.`)
    ),
    ...rogueConditions.flatMap((condition) =>
      rogueCommands.map((command) => `When ${condition}, ${command}.`)
    ),
    ...rogueConditions.flatMap((condition) =>
      rogueCommands.map((command) => `If ${condition}, ${command}.`)
    ),
  ];
}

function capitalize(value) {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function wordCount(fortune) {
  return fortune.replace(/[.;,]/g, '').trim().split(/\s+/).filter(Boolean).length;
}

function firstWords(fortune) {
  return fortune.split(/\s+/).slice(0, 2).join(' ');
}

function uniqueUnderLimit(candidates) {
  return candidates
    .map((fortune) => fortune.replace(/\s+/g, ' ').trim())
    .filter(Boolean)
    .filter((fortune, index, collection) => collection.indexOf(fortune) === index)
    .filter((fortune) => wordCount(fortune) <= 10);
}

function selectBalancedFortunes(candidates, total) {
  const source = uniqueUnderLimit(candidates);
  const selected = [];
  const used = new Set();
  const startCounts = new Map();

  for (const cap of [7, 10, 14, Number.POSITIVE_INFINITY]) {
    for (const fortune of source) {
      if (selected.length >= total) return selected;
      if (used.has(fortune)) continue;

      const start = firstWords(fortune);
      const count = startCounts.get(start) || 0;
      if (count >= cap) continue;

      selected.push(fortune);
      used.add(fortune);
      startCounts.set(start, count + 1);
    }
  }

  return selected;
}

const fortuneCandidates = [
  ...requiredFortunes,
  ...extraFortunes,
  ...observations,
  ...prompts,
  ...cautions,
  ...combine(dailyStarts, dailyEndings, 110),
  ...combine(reflectiveStarts, reflectiveEndings, 110),
  ...combine(sharpStarts, sharpEndings, 110),
  ...buildRogueFortunes(),
  ...subjects.flatMap((subject) => predicates.map((predicate) => `${subject} ${predicate}`)),
];

export const fortunes = selectBalancedFortunes(fortuneCandidates, 1500);
